# Generated by Django 6.0.2 on 2026-03-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='message',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tweet_images/')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tweetapp.tweet')),
            ],
        ),
    ]
