# Generated by Django 6.0.2 on 2026-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
