# Generated by Django 6.0.2 on 2026-03-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0011_group_groupmessage_groupinvite_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_messages/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
