# Generated by Django 5.2.12 on 2026-03-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0009_alter_comment_id_alter_like_id_alter_profile_id_and_more"),
        ("tweetapp", "0012_groupmessage_image_alter_groupmessage_message"),
    ]

    operations = []
