# Generated by Django 5.1.3 on 2026-03-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0013_groupjoinrequest"),
        ("tweetapp", "0014_alter_group_id_alter_groupinvite_id_and_more"),
    ]

    operations = []
