# Generated by Django 5.2.12 on 2026-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0015_merge_20260319_0227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupjoinrequest",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
