# Generated by Django 5.2.12 on 2026-03-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0014_tweet_visibility_follow"),
        ("tweetapp", "0016_alter_groupjoinrequest_id"),
    ]

    operations = []
