# Generated by Django 5.2.12 on 2026-03-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0015_profile_last_active"),
        ("tweetapp", "0017_merge_20260319_1533"),
    ]

    operations = []
