# Generated by Django 6.0.2 on 2026-03-20 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0020_remove_tweet_updated_at_alter_tweet_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at'], name='tweetapp_tw_created_95098a_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['nickname'], name='tweetapp_tw_nicknam_a13563_idx'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
