# Generated by Django 6.0.3 on 2026-03-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0022_alter_groupmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tweet',
            name='tweetapp_tw_created_95098a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tweet',
            name='tweetapp_tw_nicknam_a13563_idx',
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('group_invite', 'Group Invite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='message',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only')], default='public', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('group', 'invited_user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'user')},
        ),
    ]
