# Generated by Django 6.0.3 on 2026-03-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0023_alter_comment_options_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('thread', 'Thread Comment'), ('follow', 'Follow'), ('group_invite', 'Group Invite')], max_length=20),
        ),
    ]
