# Generated by Django 5.1.3 on 2026-03-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0026_alter_comment_id_alter_follow_id_and_more"),
        ("tweetapp", "0026_alter_notification_notification_type_chatthread_and_more"),
    ]

    operations = []
