# Generated by Django 5.1.3 on 2026-04-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweetapp", "0027_merge_20260331_2149"),
        ("tweetapp", "0027_pushsubscription"),
    ]

    operations = []
