# Generated by Django 6.0.2 on 2026-04-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0029_alter_comment_id_alter_follow_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('thread', 'Thread Comment'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Request Accepted'), ('group_invite', 'Group Invite'), ('message', 'Direct Message'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('comment', models.BooleanField(default=True)),
                ('thread', models.BooleanField(default=True)),
                ('follow', models.BooleanField(default=True)),
                ('follow_request', models.BooleanField(default=True)),
                ('follow_accept', models.BooleanField(default=True)),
                ('group_invite', models.BooleanField(default=True)),
                ('message', models.BooleanField(default=True)),
                ('mention', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
