# Generated by Django 6.0.2 on 2026-04-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0031_message_is_deleted_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tweetapp.groupmessage'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='group_join_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='group_mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('thread', 'Thread Comment'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Request Accepted'), ('group_invite', 'Group Invite'), ('group_join_request', 'Group Join Request'), ('group_mention', 'Group Mention'), ('message', 'Direct Message'), ('mention', 'Mention')], max_length=20),
        ),
    ]
