# Generated by Django 5.1.3 on 2026-04-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tweetapp",
            "0032_alter_chatthread_id_alter_comment_id_alter_follow_id_and_more",
        ),
        ("tweetapp", "0032_groupmembership_is_muted_groupmessage_is_deleted_and_more"),
    ]

    operations = []
