# Generated by Django 6.0.3 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0034_alter_chatthread_id_alter_comment_id_alter_follow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
