# Generated by Django 6.0.3 on 2026-04-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0035_alter_comment_message_alter_tweet_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='message',
            field=models.CharField(max_length=3000),
        ),
    ]
