# Generated by Django 6.0.3 on 2026-04-10 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0038_profile_theme_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_images', models.TextField(default='[]')),
                ('bg_selected', models.IntegerField(default=-1)),
                ('pipe_images', models.TextField(default='[]')),
                ('pipe_selected', models.IntegerField(default=-1)),
                ('bird_images', models.TextField(default='[]')),
                ('bird_selected', models.CharField(default='yellow', max_length=50)),
                ('accent_color', models.CharField(default='#10F28C', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
