# Generated by Django 6.0.2 on 2026-04-11 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0039_gamesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['game', '-score'], name='tweetapp_ga_game_a646d5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['user', 'game', '-created_at'], name='tweetapp_ga_user_id_f0aa56_idx'),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['game', 'created_at'], name='tweetapp_ga_game_3c0803_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='tweetapp_me_thread__a0214c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'is_read'], name='tweetapp_me_thread__ac286d_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at'], name='tweetapp_tw_created_95098a_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user', '-created_at'], name='tweetapp_tw_user_id_313006_idx'),
        ),
    ]
