# Generated by Django 6.0.2 on 2026-04-12 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0040_alter_profile_last_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tweet', '-created_at'], name='tweetapp_co_tweet_i_910525_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='tweetapp_no_recipie_04bc09_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='tweetapp_no_recipie_278690_idx'),
        ),
    ]
