from django.urls import path
from . import views
app_name = 'tweetapp'
urlpatterns = [
    path('', views.listtweet, name = 'listtweet'), #ardakorkmaz.com/tweetapp/
    path('addtweet/',views.addtweet, name= 'addtweet'), #ardakorkmaz.com/tweetapp/addtweet/
    path('addtweetbyform/', views.addtweetbyform, name = 'addtweetbyform'), #ardakorkmaz.com/tweetapp/addtweetbyform/
    path('addtweetbymodelform',views.addtweetbymodelform, name="addtweetbymodelform"), #ardakorkmaz.com/tweetapp/addtweetbymodelform/
    path('search/', views.searchtweet, name='searchtweet'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/followers-following/', views.followers_following, name='followers_following'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('register/',views.RegisterView.as_view(), name="register"),
    path('delete/<int:pk>/', views.delete_tweet, name='delete_tweet'),
    path('like/<int:pk>/', views.like_tweet, name='like_tweet'),
    path('comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('delete-comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('users/', views.userlist, name='userlist'),
    path('edit/<int:pk>/', views.edit_tweet, name='edit_tweet'),
    path('patchnotes/', views.patchnotes, name='patchnotes'),
    path('patchnotes/add/', views.add_patchnote, name='add_patchnote'),
    path('patchnotes/delete/<int:pk>/', views.delete_patchnote, name='delete_patchnote'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.create_group, name='create_group'),
    path('groups/<int:pk>/', views.group_detail, name='group_detail'),
    path('groups/<int:pk>/send/', views.group_send_message, name='group_send_message'),
    path('groups/<int:pk>/join/', views.group_join, name='group_join'),
    path('groups/<int:pk>/leave/', views.group_leave, name='group_leave'),
    path('groups/<int:pk>/invite/', views.group_invite, name='group_invite'),
    path('groups/<int:pk>/kick/<int:user_id>/', views.group_kick, name='group_kick'),
    path('groups/<int:pk>/delete/', views.group_delete, name='group_delete'),
    path('invite/accept/<int:pk>/', views.group_accept_invite, name='group_accept_invite'),
    path('invite/decline/<int:pk>/', views.group_decline_invite, name='group_decline_invite'),
    path('groups/<int:pk>/request/', views.group_request_join, name='group_request_join'),
    path('request/accept/<int:pk>/', views.group_accept_request, name='group_accept_request'),
    path('request/decline/<int:pk>/', views.group_decline_request, name='group_decline_request'),
    path('follow/<str:username>/', views.follow_user, name='follow_user'),
    path('visibility/<int:pk>/', views.toggle_visibility, name='toggle_visibility'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('tweet/<int:pk>/', views.tweet_detail, name='tweet_detail'),
]